# Generated by Django 5.2.5 on 2025-08-15 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, default='python', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
