# Generated by Django 5.0.2 on 2025-10-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_alter_comment_options_comment_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "مقاله", "verbose_name_plural": "مقاله ها"},
        ),
    ]
